server:
  port: 8088
spring:
  redis:
    host: 172.20.24.130
    port: 6379
    password: 651tkoOuMeQzxLZfFUAv
    database: 3
    lettuce:
      pool:
        max-active: 1024 # 最大连接数 默认 8
        max-wait: 10000 # 最大连接阻塞等待时间 单位毫秒 默认-1
        max-idle: 200 # 最大空闲连接
        min-idle: 5     #最小空闲连接
    timeout: 10000